import Head from 'next/head';
import Nav from '../templates/layout/nav';
import General from '../templates/components/general';
import { dataHome } from '../api-data/home';

import About from '../templates/components/about';
import { dataAbout } from '../api-data/about';

import Service from '../templates/components/service';
import { dataService } from '../api-data/service';

import Portfolio from '../templates/components/post';
import { dataPort } from '../api-data/port';

import Testimonials from '../templates/components/testimonials';
import { dataTestimonials } from '../api-data/testimonials';

import Blog from '../templates/components/blog';
import { dataBlog } from '../api-data/blog';

import Contact from '../templates/components/contact';
import { dataContact } from '../api-data/contact';

import { useEffect } from 'react';
// import
export default function Home() {
  const ID = ['data1', 'data2', 'data3', 'data4', 'data5', 'data6', 'data7'];

  return (
    <div className='site'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='main'>
        <div className='Nav'>
          <Nav ID={ID} />
        </div>
        <div className='body'>
          <General id={ID[0]} data={dataHome} />
          <About id={ID[1]} data={dataAbout} />
          <Service id={ID[2]} data={dataService} />
          <Portfolio id={ID[3]} data={dataPort} />
          <Testimonials id={ID[4]} data={dataTestimonials} />
          <Blog id={ID[5]} data={dataBlog} />
          <Contact id={ID[6]} data={dataContact} />
        </div>
      </main>
    </div>
  );
}
